### ISSUE TITLE
fdist software download error

### ISSUE THREAD

**Issue by yuntwang** [tiagoantao/my-containers#1]
Hi,
I follow the method you provide:
#fdist
RUN mkdir fdist2
WORKDIR /fdist2
RUN wget http://www.maths.bris.ac.uk/~mamab/software/fdist2.zip
RUN unzip fdist2.zip
RUN gcc -o fdist2 -O fdist2.c -lm
RUN gcc -o cplot -O cplot.c as100.c as99.c -lm
RUN gcc -o pv -O pv.c as100.c as99.c -lm
RUN gcc -o datacal -O datacal.c -lm
RUN cp datacal pv cplot fdist2 /usr/bin
WORKDIR /
RUN rm -rf fdist2

But I can't access the " http://www.maths.bris.ac.uk/~mamab/software/fdist2.zip"!
Can you send me this software.
My  email:1006298144@qq.cm
Thanks.

**Comment by tiagoantao** [comment]
Thanks for the report.

I removed fdist2 and a some other software that is not supported by Biopython anymore.

It should work now. Tell me if not.

**Comment by yuntwang** [comment]
Hi,
@tiagoantao 
When I tried access the URL:https://people.maths.bris.ac.uk/~mamab/software/
I get :

**Not Found

The requested URL /~mamab/software/ was not found on this server.**

I am from china and permission denied?
